# Generated by Django 4.1.4 on 2022-12-30 01:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Test",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "following",
                    models.ManyToManyField(
                        blank=True, related_name="followers", to="api.user"
                    ),
                ),
                ("friends", models.ManyToManyField(blank=True, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=200)),
                (
                    "description",
                    models.CharField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("members", models.ManyToManyField(blank=True, to="api.user")),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("likes", models.IntegerField(blank=True, default=0, null=True)),
                ("dislikes", models.IntegerField(blank=True, default=0, null=True)),
                ("comments", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "langauge",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "flair",
                    models.CharField(blank=True, default="", max_length=200, null=True),
                ),
                (
                    "space",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.space",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        blank=True, default="", max_length=2000, null=True
                    ),
                ),
                ("up_votes", models.IntegerField(blank=True, default=0, null=True)),
                ("date", models.DateTimeField(auto_now_add=True, null=True)),
                ("comments", models.ManyToManyField(blank=True, to="api.comment")),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.post",
                    ),
                ),
                (
                    "reply_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.comment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.user",
                    ),
                ),
            ],
        ),
    ]
