# Generated by Django 4.1 on 2022-12-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_post_hascode_alter_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='room',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
