# Generated by Django 4.1 on 2022-12-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_post_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='flair',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
