# Generated by Django 4.1.4 on 2023-01-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_technology_rename_langauge_post_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='question',
            field=models.CharField(blank=True, default='', max_length=2000, null=True),
        ),
    ]
