# Generated by Django 4.1 on 2022-12-26 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_space_remove_post_room_post_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='members',
        ),
        migrations.AddField(
            model_name='space',
            name='members',
            field=models.ManyToManyField(blank=True, to='api.user'),
        ),
    ]
