# Generated by Django 4.1.4 on 2023-01-14 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_post_likes_alter_post_user_vote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
