# Generated by Django 4.1.4 on 2023-01-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_post_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.RemoveField(
            model_name='post',
            name='voted_users',
        ),
        migrations.AddField(
            model_name='post',
            name='liked_by',
            field=models.ManyToManyField(related_name='posts_liked', through='api.Vote', to='api.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
