# Generated by Django 4.1.4 on 2023-01-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_test_remove_post_voted_users_post_liked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
