# Generated by Django 4.1.4 on 2023-01-16 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_images_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
        migrations.AddField(
            model_name='space',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
